### ISSUE TITLE
External reading

### ISSUE THREAD

**Issue by Spyro1502** [BenjaminAster/Aster.js#1]
Hi !

I was just wondering if there were a way to make a discord bot able to read it, or at least detect it, I haven't been able to really understand your code

**Comment by BenjaminAster** [comment]
Hi!
How did you find my repository? Did you just randomly stumble across it? Because it is definitely not yet meant for public use. This is still in VERY early development. 
And I don't know what this should have to do with a Discord bot, to be honest. If you are on Windows, you can run:
`deno run --unstable --allow-run --allow-read="." --allow-write="." ./src/index.deno.ts`
from the root folder of this repository to start compiling your "test.aster"-file. In the `build` folder, you then find your updated `index.html` and the JavaScript and CSS files. 
As I said, this is not yet ready for public use, but if you want to, I can give you a short introduction.
